model = "gpt-5.4"
review_model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"
model_reasoning_summary = "auto"
model_verbosity = "high"
personality = "pragmatic"
disable_response_storage = true
sandbox_mode = "danger-full-access"
windows_wsl_setup_acknowledged = true
approval_policy = "never"
profile = "auto-max"
file_opener = "vscode"
model_provider = "gmn"
web_search = "cached"
suppress_unstable_features_warning = true

[history]
persistence = "save-all"

[tui]
notifications = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = false

[sandbox_workspace_write]
network_access = true

[features]
apply_patch_freeform = true
unified_exec = false
elevated_windows_sandbox = true
multi_agent = true
shell_tool = true
shell_snapshot = true
fast_mode = true
personality = true

[profiles.auto-max]
approval_policy = "never"
sandbox_mode = "workspace-write"

[profiles.review]
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[notice]
hide_gpt5_1_migration_prompt = true

[model_providers.gmn]
name = "gmn"
base_url = "https://ai.gmncode.com"
wire_api = "responses"
requires_openai_auth = true
